name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      
    - name: Pnpm-setup
      uses: pnpm/action-setup@v2
      with:
        version: next-8
        standalone: true

    - name: Install packages
      run: pnpm install --frozen-lockfile

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Build  
      run: pnpm run build

    - name: Tests
      run: pnpm test
