name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: 
          - latest
          - canary

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      
    - name: Bun-setup
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}

    - name: Install packages
      run: bun install --frozen-lockfile
        
    - name: Build  
      run: bun run build

    - name: Tests
      run: bun test
